/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;

// module.exports = {
//   someSidebar: {
//     "Getting started": ['system-prerequisites', 'installation-guide', 'supported-browsers'],
//     'Backend development': [
//       'development/technical-overview',
//       'development/directory-structure',
//       'development/module',
//       'development/module-development',
//       'development/middleware',
//       'development/working-with-database',
//       'development/routing',
//       'development/event-dispatcher',
//       'development/services',
//       'development/graphql',
//       'development/promises'
//     ],
//     'Frontend development': [
//       'development/client-side-rendering',
//       'development/templates-overview',
//       'development/area-and-widget',
//       'development/theming-overview'
//     ],
//     "Tutorials": [
//       "tutorials/how-to-create-a-module"
//     ]
//   },
// };
