/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'development' }],
  apiSidebar: [
    'api/overview',
    {
      type: 'category',
      label: 'Attribute',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/attribute',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute#create-an-attribute"><span class="method POST">POST</span><span>Create an attribute</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute#update-an-attribute"><span class="method PATCH">PATCH</span><span>Update an attribute</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute#delete-an-attribute"><span class="method DELETE">DELETE</span><span>Delete an attribute</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Attribute Group',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/attribute-group',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute-group#create-an-attribute-group"><span class="method POST">POST</span><span>Create an attribute group</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute-group#update-an-attribute-group"><span class="method PATCH">PATCH</span><span>Update an attribute group</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/attribute-group#delete-an-attribute-group"><span class="method DELETE">DELETE</span><span>Delete an attribute group</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Product',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/product',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/product#create-a-product"><span class="method POST">POST</span><span>Create a product</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/product#update-a-product"><span class="method PATCH">PATCH</span><span>Update a product</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/product#delete-a-product"><span class="method DELETE">DELETE</span><span>Delete a product</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Variant',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/variant',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/variant#create-a-variant-group"><span class="method POST">POST</span><span>Create a variant group</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/variant#add-variant-item"><span class="method POST">POST</span><span>Add variant item</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Category',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/category',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/category#create-a-category"><span class="method POST">POST</span><span>Create a category</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/category#update-a-category"><span class="method PATCH">PATCH</span><span>Update a category</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/category#delete-a-category"><span class="method DELETE">DELETE</span><span>Delete a category</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Cart',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/cart',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#add-item-to-cart"><span class="method POST">POST</span><span>Add item to cart</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#remove-item-from-cart"><span class="method DELETE">DELETE</span><span>Remove item from cart</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#add-customer-info"><span class="method POST">POST</span><span>Add customer info</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#add-address"><span class="method POST">POST</span><span>Add address</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#add-shipping-method"><span class="method POST">POST</span><span>Add shipping method</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cart#add-payment-method"><span class="method POST">POST</span><span>Add payment method</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Payment Methods',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/payment-method',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/payment-method#get-available-payment-methods"><span class="method GET">GET</span><span>Get payment methods</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Shipping Methods',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/shipping-method',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/shipping-method#get-available-shipping-methods"><span class="method GET">GET</span><span>Get shipping methods</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Promotion',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/promotion',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/promotion#create-a-coupon"><span class="method POST">POST</span><span>Create a coupon</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/promotion#update-a-coupon"><span class="method PATCH">PATCH</span><span>Update a coupon</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/promotion#delete-a-coupon"><span class="method DELETE">DELETE</span><span>Delete a coupon</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/promotion#apply-a-coupon"><span class="method POST">POST</span><span>Apply a coupon</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Order',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/order',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/order#create-an-order"><span class="method POST">POST</span><span>Create an order</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/order#create-a-shipment"><span class="method POST">POST</span><span>Create a shipment</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/order#update-a-shipment"><span class="method PATCH">PATCH</span><span>Update a shipment</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Customer',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/customer',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/customer#create-a-customer"><span class="method POST">POST</span><span>Create a customer</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/customer#update-a-customer"><span class="method PATCH">PATCH</span><span>Update a customer</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/customer#delete-a-customer"><span class="method DELETE">DELETE</span><span>Delete a customer</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/customer#create-a-customer-session"><span class="method POST">POST</span><span>Create a customer session</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/customer#delete-a-customer-session"><span class="method DELETE">DELETE</span><span>Delete a customer session</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'User',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/user',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/user#create-a-user-session"><span class="method POST">POST</span><span>Create a user session</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/user#delete-a-user-session"><span class="method DELETE">DELETE</span><span>Delete a user session</span></a>',
        }
      ]
    },
    {
      type: 'category',
      label: 'Cms Page',
      className: 'api-menu-item',
      link: {
        type: 'doc',
        id: 'api/cms-page',
      },
      items: [
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cms-page#create-a-page"><span class="method POST">POST</span><span>Create a page</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cms-page#update-a-page"><span class="method PATCH">PATCH</span><span>Update a page</span></a>',
        },
        {
          type: 'html',
          value: '<a class="menu__link" href="/docs/api/cms-page#delete-a-page"><span class="method DELETE">DELETE</span><span>Delete a page</span></a>',
        }
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
